# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxProject/HDMI_test/HDMI_test.srcs/sources_1/ip/v_hdmi_rx_ss_0/v_hdmi_rx_ss_0.xci
# IP: The module: 'v_hdmi_rx_ss_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/bd_2422_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2422_0 || ORIG_REF_NAME==bd_2422_0} -quiet] -quiet

# IP: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_2422_0_v_hdmi_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2422_0_v_hdmi_rx_0 || ORIG_REF_NAME==bd_2422_0_v_hdmi_rx_0} -quiet] -quiet

# IP: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_1/bd_2422_0_v_vid_in_axi4s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2422_0_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_2422_0_v_vid_in_axi4s_0} -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/bd_2422_0_ooc.xdc

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/v_hdmi_rx_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_hdmi_rx_ss_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/XilinxProject/HDMI_test/HDMI_test.srcs/sources_1/ip/v_hdmi_rx_ss_0/v_hdmi_rx_ss_0.xci
# IP: The module: 'v_hdmi_rx_ss_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/bd_2422_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2422_0 || ORIG_REF_NAME==bd_2422_0} -quiet] -quiet

# IP: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_2422_0_v_hdmi_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2422_0_v_hdmi_rx_0 || ORIG_REF_NAME==bd_2422_0_v_hdmi_rx_0} -quiet] -quiet

# IP: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/ip/ip_1/bd_2422_0_v_vid_in_axi4s_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2422_0_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_2422_0_v_vid_in_axi4s_0} -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/bd_0/bd_2422_0_ooc.xdc

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_rx_ss_0/v_hdmi_rx_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_hdmi_rx_ss_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
