# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxProject/HDMI_test/HDMI_test.srcs/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0.xci
# IP: The module: 'vid_phy_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/ip_0/vid_phy_controller_0_gtwrapper.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==vid_phy_controller_0_gtwrapper} -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/ip_0/vid_phy_controller_0_gtwrapper.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==vid_phy_controller_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/ip_0/vid_phy_controller_0_gtwrapper_ooc.xdc

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/XilinxProject/HDMI_test/HDMI_test.srcs/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0.xci
# IP: The module: 'vid_phy_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/ip_0/vid_phy_controller_0_gtwrapper.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==vid_phy_controller_0_gtwrapper} -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/ip_0/vid_phy_controller_0_gtwrapper.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==vid_phy_controller_0_gtwrapper || ORIG_REF_NAME==vid_phy_controller_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/ip_0/vid_phy_controller_0_gtwrapper_ooc.xdc

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/vid_phy_controller_0/vid_phy_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_phy_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
