# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_2444_0_axi_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2444_0_axi_crossbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/XilinxProject/HDMI_test/HDMI_test.gen/sources_1/ip/v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_2444_0_axi_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2444_0_axi_crossbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
